### PR TITLE
Fix example project dependencies

### PR DESCRIPTION
**Pull request by KestasVenslauskas**
Added "react-native-theoplayer" dependency as project folder in example project.

### CODE REVIEW

**Comment by KestasVenslauskas** [comment]
Example project had only native android dependency for react-native-theoplayer but not on react side. So I guess I fixed it? Unless there is a reason for this structure?

**Comment by tvanlaerhoven** [comment]
@KestasVenslauskas, the React dependency is created with an alias in the [babel config file](https://github.com/THEOplayer/react-native-theoplayer/blob/master/example/babel.config.js).

The idea is that during babel processing, all react-native-theoplayer imports are redirected to the original source, instead of pulling in a copy of react-native-theoplayer during an `npm install`. This is not what you normally do in your app, but for the example app the benefit is that you can develop both the `react-native-theoplayer` and example app together: metro detects and rebundles code changes in both.

**Comment by KestasVenslauskas** [comment]
And you don't get any IDE errors?

**Comment by tvanlaerhoven** [comment]
You'll need to open the project from the react-native-theoplayer (root) folder, not the example subfolder. In that case the IDE is able to resolve any `react-native-theoplayer` references in your code. It works for both Webstorm and VS.

I guess we need to add this to the documentation indeed.

**Pull request closed without merging**
