### PR TITLE
Deprecate Jitpack

### PR DESCRIPTION
**Pull request by ceyhun-o**
Replaces Jitpack with our own Maven repo.

### CODE REVIEW

**Comment by tvanlaerhoven** [comment]
Thanks @ceyhun-o !

There was one issue with this when I tried it before: react-native itself adds Jitpack.io as a repository source, so when resolving dependencies, it would still go first to Jitpack.io. During a release it takes some time before Jitpack resolves the dependency, so we could end up with a mix of core versions from Jitpack and connector versions from maven.theoplayer for example.

A `implementation "com.theoplayer.theoplayer-sdk-android:core:+"` dependency for example will always resolve to Jitpack first and get the latest dependency there. Not sure how to resolve this currently.

**Comment by ceyhun-o** [comment]
> we could end up with a mix of core versions from Jitpack and connector versions from maven.theoplayer for example.

Once we stop publishing to Jitpack (on one of the next major releases), couldn't we prevent this by locking RN SDK's minimum supported version to that major version? Since that major version will not exist on Jitpack, everything should be fetched from THEOplayer Maven.

On the current setup it should not be an issue if some libraries are fetched from Jitpack instead of Maven since they are identical.

**Comment by tvanlaerhoven** [comment]
> > we could end up with a mix of core versions from Jitpack and connector versions from maven.theoplayer for example.
> 
> Once we stop publishing to Jitpack (on one of the next major releases), couldn't we prevent this by locking RN SDK's minimum supported version to that major version? Since that major version will not exist on Jitpack, everything should be fetched from THEOplayer Maven.

Indeed, let's merge this PR in react-native-theoplayer 8.0 somewhere next week!

**Comment by MattiasBuelens** [comment]
> There was one issue with this when I tried it before: react-native itself adds Jitpack.io as a repository source, so when resolving dependencies, it would still go first to Jitpack.io. During a release it takes some time before Jitpack resolves the dependency, so we could end up with a mix of core versions from Jitpack and connector versions from maven.theoplayer for example.

Can't you put `maven.theoplayer.com` before `jitpack.io` in your `repositories`? IIRC Gradle will try to fetch each dependency from those repositories *in the specified order*, so it will try our official Maven repository first.

**Pull request merged**
